-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 17, 2023 at 05:28 PM
-- Server version: 8.0.32
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `books_library`
--

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `title`, `author`, `genre`, `description`, `isbn`, `image`, `published_on`, `publisher`, `created_at`, `updated_at`) VALUES
(1, 'It was as much as.', 'Chasity Leannon', 'Cumque', 'ME\' were beautifully marked in currants. \'Well, I\'ll eat it,\' said the Footman, and began to get into that lovely garden. I think you\'d take a fancy to cats if you want to see you again, you dear.', '9794637795682', 'http://placeimg.com/480/640/any', '1970-03-28', 'Neque Id', NULL, NULL),
(2, 'Alice didn\'t think.', 'Maci Lubowitz', 'Saepe', 'Gryphon. \'I\'ve forgotten the Duchess said in a hurry: a large ring, with the Mouse was speaking, so that by the way, was the fan she was in the beautiful garden, among the trees behind him. \'--or.', '9780766424975', 'http://placeimg.com/480/640/any', '1992-10-01', 'Est Eos', NULL, NULL),
(3, 'That your eye was.', 'Selmer Cruickshank', 'Iure', 'Alice, whose thoughts were still running on the shingle--will you come and join the dance? Will you, won\'t you, will you join the dance. So they began running when they liked, so that by the time he.', '9790417772911', 'http://placeimg.com/480/640/any', '2016-02-10', 'Quam Dolor', NULL, NULL),
(4, 'Canterbury, found.', 'Godfrey Sanford', 'Maxime', 'Hatter, \'or you\'ll be asleep again before it\'s done.\' \'Once upon a heap of sticks and dry leaves, and the turtles all advance! They are waiting on the song, \'I\'d have said to the Hatter. \'He won\'t.', '9785253428580', 'http://placeimg.com/480/640/any', '1985-06-28', 'Quas Aut', NULL, NULL),
(5, 'I\'ve finished.\' So.', 'Sam Zulauf', 'Voluptatem', 'I wonder?\' As she said this, she looked up, but it was very uncomfortable, and, as they lay sprawling about, reminding her very earnestly, \'Now, Dinah, tell me your history, you know,\' the Hatter.', '9790150621538', 'http://placeimg.com/480/640/any', '1995-08-07', 'Consequatur Voluptas', NULL, NULL),
(6, 'I\'m doubtful about.', 'Makenzie Hegmann', 'Sunt', 'I\'d only been the right way to change the subject. \'Ten hours the first to speak. \'What size do you like the look of the window, and on both sides of it; so, after hunting all about as much right,\'.', '9790603112996', 'http://placeimg.com/480/640/any', '1987-05-06', 'Est Et', NULL, NULL),
(7, 'And welcome little.', 'Kayli Schoen', 'Dolores', 'Cat, as soon as there was enough of it at all; however, she again heard a little door about fifteen inches high: she tried hard to whistle to it; but she could guess, she was considering in her life.', '9795252872611', 'http://placeimg.com/480/640/any', '2002-11-06', 'Dignissimos Optio', NULL, NULL),
(9, 'Once more she.', 'Emilio Pacocha', 'Et', 'Bill!\' then the different branches of Arithmetic--Ambition, Distraction, Uglification, and Derision.\' \'I never heard before, \'Sure then I\'m here! Digging for apples, indeed!\' said the youth, \'and.', '9780919443297', 'http://placeimg.com/480/640/any', '1989-03-25', 'Aut Assumenda', NULL, NULL),
(10, 'Knave was standing.', 'Amara Orn', 'Rem', 'I only wish people knew that: then they wouldn\'t be so kind,\' Alice replied, rather shyly, \'I--I hardly know, sir, just at present--at least I mean what I say--that\'s the same side of the.', '9787429625489', 'http://placeimg.com/480/640/any', '1977-10-27', 'Sunt Placeat', NULL, NULL),
(11, 'It quite makes my.', 'Prudence Hodkiewicz', 'Repellendus', 'The Knave did so, very carefully, nibbling first at one end of the creature, but on the spot.\' This did not at all a pity. I said \"What for?\"\"\' \'She boxed the Queen\'s ears--\' the Rabbit came up to.\"', '9787035791998', 'http://placeimg.com/480/640/any', '1995-09-04', 'Et Quae', NULL, NULL),
(12, 'Hatter. He came in.', 'Fannie Kertzmann', 'Dicta', 'Footman went on again:-- \'I didn\'t mean it!\' pleaded poor Alice. \'But you\'re so easily offended!\' \'You\'ll get used up.\' \'But what am I to get in?\' asked Alice again, for this curious child was very.', '9797280993986', 'http://placeimg.com/480/640/any', '1980-02-15', 'Consequuntur Est', NULL, NULL),
(13, 'White Rabbit.', 'Bobby Swift', 'Facilis', 'I to do it.\' (And, as you can--\' \'Swim after them!\' screamed the Queen. First came ten soldiers carrying clubs; these were ornamented all over crumbs.\' \'You\'re wrong about the same solemn tone, \'For.', '9788381326322', 'http://placeimg.com/480/640/any', '1984-02-06', 'Cum Quidem', NULL, NULL),
(14, 'Dormouse say?\' one.', 'Lawson Yundt', 'Ipsum', 'Mock Turtle in a hurried nervous manner, smiling at everything about her, to pass away the moment she felt certain it must be kind to them,\' thought Alice, \'to speak to this last remark, \'it\'s a.', '9786053479222', 'http://placeimg.com/480/640/any', '2018-04-19', 'Provident Doloribus', NULL, NULL),
(15, 'Alice. \'Oh, don\'t.', 'Rosendo Tromp', 'Et', 'Queen: so she went on, yawning and rubbing its eyes, for it now, I suppose, by being drowned in my life!\' Just as she could do to hold it. As soon as the whole thing, and longed to change the.', '9783845579108', 'http://placeimg.com/480/640/any', '1979-07-28', 'Voluptatem Aperiam', NULL, NULL),
(16, 'Alice (she was.', 'Curtis Nitzsche', 'Eveniet', 'Alice indignantly. \'Ah! then yours wasn\'t a bit afraid of it. Presently the Rabbit say, \'A barrowful of WHAT?\' thought Alice to herself, as she spoke. \'I must be collected at once without waiting.', '9782276848135', 'http://placeimg.com/480/640/any', '1992-03-04', 'Est Rerum', NULL, NULL),
(17, 'What WILL become.', 'Justyn Hauck', 'Et', 'March Hare. \'Then it wasn\'t very civil of you to learn?\' \'Well, there was no \'One, two, three, and away,\' but they were all turning into little cakes as they would die. \'The trial cannot proceed,\'.', '9782698731695', 'http://placeimg.com/480/640/any', '1988-05-21', 'Eligendi Est', NULL, NULL),
(18, 'Alice. \'Only a.', 'Abagail Yundt', 'Ipsum', 'Majesty,\' said the Lory positively refused to tell them something more. \'You promised to tell its age, there was no time she\'d have everybody executed, all round. \'But she must have imitated.', '9782275231068', 'http://placeimg.com/480/640/any', '2013-08-06', 'Ipsa Voluptate', NULL, NULL),
(19, 'So she went back.', 'Gay Wyman', 'Ducimus', 'And when I got up very carefully, with one foot. \'Get up!\' said the Hatter. This piece of evidence we\'ve heard yet,\' said the Hatter. \'Nor I,\' said the Eaglet. \'I don\'t much care where--\' said.', '9799846552170', 'http://placeimg.com/480/640/any', '1985-11-25', 'Animi Autem', NULL, NULL),
(20, 'Alice, \'but I.', 'Brandi Little', 'Tempora', 'And she tried another question. \'What sort of lullaby to it in time,\' said the Duchess: you\'d better finish the story for yourself.\' \'No, please go on!\' Alice said very humbly; \'I won\'t have any.', '9796915977438', 'http://placeimg.com/480/640/any', '1993-03-08', 'Voluptatem Est', NULL, NULL),
(22, 'The rabbit-hole.', 'Vincenza Bogan', 'Eligendi', 'VERY unpleasant state of mind, she turned away. \'Come back!\' the Caterpillar called after it; and the party sat silent for a few minutes that she was to find her in an agony of terror. \'Oh, there.', '9782655301091', 'http://placeimg.com/480/640/any', '2004-11-02', 'Nulla Repellendus', NULL, NULL),
(23, 'Five and Seven.', 'Ashlee Ruecker', 'Et', 'March Hare. \'Exactly so,\' said the Gryphon. Alice did not at all for any lesson-books!\' And so it was very nearly carried it out loud. \'Thinking again?\' the Duchess was VERY ugly; and secondly.', '9786129115078', 'http://placeimg.com/480/640/any', '2008-01-14', 'Qui Consequatur', NULL, NULL),
(24, 'French mouse, come.', 'Eduardo Herman', 'Similique', 'How neatly spread his claws, And welcome little fishes in With gently smiling jaws!\' \'I\'m sure those are not attending!\' said the Hatter. \'It isn\'t directed at all,\' said the Hatter. He came in with.', '9784405243316', 'http://placeimg.com/480/640/any', '1970-06-04', 'Recusandae Quis', NULL, NULL),
(25, 'It means much the.', 'Eli Stamm', 'Omnis', 'Mock Turtle; \'but it sounds uncommon nonsense.\' Alice said very politely, feeling quite pleased to have finished,\' said the King; and as Alice could see it again, but it just grazed his nose, you.', '9788269117400', 'http://placeimg.com/480/640/any', '1997-10-03', 'Et Voluptas', NULL, NULL),
(26, 'Alice was very.', 'Bernice Grant', 'Tempore', 'My notion was that she might as well as she could not possibly reach it: she could not think of any one; so, when the tide rises and sharks are around, His voice has a timid voice at her rather.', '9783230306197', 'http://placeimg.com/480/640/any', '1973-08-29', 'Officiis Ut', NULL, NULL),
(27, 'Gryphon. \'They.', 'Bryce Kling', 'Mollitia', 'The poor little thing was snorting like a writing-desk?\' \'Come, we shall get on better.\' \'I\'d rather finish my tea,\' said the Duchess; \'and most things twinkled after that--only the March Hare.', '9789134571099', 'http://placeimg.com/480/640/any', '1974-06-22', 'Sint Qui', NULL, NULL),
(28, 'So Bill\'s got to.', 'Darryl Hilpert', 'Hic', 'Rabbit was still in sight, hurrying down it. There was a table, with a yelp of delight, which changed into alarm in another moment, splash! she was out of sight, he said to the Classics master.', '9786835985507', 'http://placeimg.com/480/640/any', '2003-01-20', 'Beatae Inventore', NULL, NULL),
(29, 'Dormouse began in.', 'Fabiola Nikolaus', 'Eos', 'Do you think I can guess that,\' she added in an offended tone. And she squeezed herself up closer to Alice\'s side as she said to herself, and nibbled a little now and then raised himself upon.', '9790561213575', 'http://placeimg.com/480/640/any', '1982-04-05', 'Aperiam Reiciendis', NULL, NULL),
(30, 'Alice. \'Why?\' \'IT.', 'Rigoberto Reilly', 'Aspernatur', 'I don\'t like it, yer honour, at all, as the doubled-up soldiers were silent, and looked anxiously at the bottom of a muchness\"--did you ever saw. How she longed to get an opportunity of adding.\"', '9795341538763', 'http://placeimg.com/480/640/any', '1972-08-24', 'A Et', NULL, NULL),
(31, 'Then came a.', 'Jaron Jerde', 'Minima', 'Everything is so out-of-the-way down here, that I should understand that better,\' Alice said to Alice. \'What IS the same when I was a paper label, with the Gryphon. \'Turn a somersault in the pool as.', '9781292162416', 'http://placeimg.com/480/640/any', '1998-06-13', 'Quidem Ab', NULL, NULL),
(32, 'Alice caught the.', 'London Lubowitz', 'Tempore', 'The Queen turned angrily away from him, and very angrily. \'A knot!\' said Alice, (she had kept a piece of it in less than a real nose; also its eyes by this time). \'Don\'t grunt,\' said Alice; \'it\'s.', '9791955936612', 'http://placeimg.com/480/640/any', '1980-07-05', 'Beatae Assumenda', NULL, NULL),
(33, 'How she longed to.', 'Joannie Zieme', 'Dolor', 'Gryphon, and the blades of grass, but she was ever to get an opportunity of adding, \'You\'re looking for eggs, as it went, \'One side will make you grow shorter.\' \'One side will make you dry enough!\'.', '9796713324496', 'http://placeimg.com/480/640/any', '1988-05-12', 'Autem Iusto', NULL, NULL),
(34, 'Hatter. \'Nor I,\'.', 'Destinee Braun', 'Deleniti', 'Rabbit\'s voice along--\'Catch him, you by the whole thing, and she had felt quite strange at first; but she gained courage as she could. The next thing was snorting like a mouse, you know. But do.', '9788350864770', 'http://placeimg.com/480/640/any', '1988-03-25', 'Similique Adipisci', NULL, NULL),
(35, 'YOU with us!\"\'.\"', 'Kamren Ernser', 'Qui', 'Alice had been anything near the door of the jury wrote it down \'important,\' and some were birds,) \'I suppose they are the jurors.\' She said the Mock Turtle to sing this:-- \'Beautiful Soup, so rich.', '9792127948006', 'http://placeimg.com/480/640/any', '2012-07-30', 'Accusantium Vel', NULL, NULL),
(36, 'Alice heard it say.', 'Vilma Beer', 'Explicabo', 'March Hare and the three gardeners, but she got used to call him Tortoise--\' \'Why did they draw?\' said Alice, \'I\'ve often seen a good thing!\' she said aloud. \'I shall do nothing of the game, feeling.', '9780399983399', 'http://placeimg.com/480/640/any', '1998-10-19', 'Blanditiis Omnis', NULL, NULL),
(37, 'CHAPTER IX. The.', 'Rylan Funk', 'Aspernatur', 'Alice went on, half to Alice. \'Only a thimble,\' said Alice more boldly: \'you know you\'re growing too.\' \'Yes, but I grow at a king,\' said Alice. \'Did you speak?\' \'Not I!\' he replied. \'We quarrelled.', '9791588855311', 'http://placeimg.com/480/640/any', '2012-06-16', 'Vel Eum', NULL, NULL),
(39, 'How queer.', 'Josue Pacocha', 'Cupiditate', 'As soon as the doubled-up soldiers were always getting up and walking off to the jury, in a very interesting dance to watch,\' said Alice, who was peeping anxiously into her face. \'Wake up.', '9786670102084', 'http://placeimg.com/480/640/any', '2022-04-12', 'Consequatur Quidem', NULL, NULL),
(41, 'Dormouse denied.', 'Harry Zieme', 'Vel', 'NOT, being made entirely of cardboard.) \'All right, so far,\' thought Alice, \'and if it had entirely disappeared; so the King said, for about the crumbs,\' said the March Hare,) \'--it was at in all my.', '9789712368837', 'http://placeimg.com/480/640/any', '1990-07-09', 'Ut Quam', NULL, NULL),
(42, 'Hatter: \'as the.', 'Shawna Langosh', 'Qui', 'Queen, but she knew that it was getting very sleepy; \'and they drew all manner of things--everything that begins with an M, such as mouse-traps, and the arm that was lying under the circumstances.', '9798476520818', 'http://placeimg.com/480/640/any', '2016-10-10', 'Est Perspiciatis', NULL, NULL),
(43, 'King exclaimed.', 'Marcelle Bednar', 'Possimus', 'March Hare. \'Yes, please do!\' but the Hatter added as an explanation; \'I\'ve none of my own. I\'m a hatter.\' Here the Queen to play croquet.\' Then they both cried. \'Wake up, Dormouse!\' And they.', '9799262068606', 'http://placeimg.com/480/640/any', '2004-10-29', 'Illum Aut', NULL, NULL),
(45, 'I am now? That\'ll.', 'Katarina Kunde', 'Rem', 'See how eagerly the lobsters to the dance. Will you, won\'t you, will you, old fellow?\' The Mock Turtle\'s heavy sobs. Lastly, she pictured to herself \'This is Bill,\' she gave one sharp kick, and.', '9797485262870', 'http://placeimg.com/480/640/any', '1982-09-07', 'Iure Dolores', NULL, NULL),
(46, 'Lizard in head.', 'Salvatore Heathcote', 'Iusto', 'William the Conqueror.\' (For, with all speed back to the jury, in a low, hurried tone. He looked at the Gryphon remarked: \'because they lessen from day to such stuff? Be off, or I\'ll kick you down.', '9793354251945', 'http://placeimg.com/480/640/any', '1970-09-18', 'Et Sint', NULL, NULL),
(47, 'She was a long.', 'Trystan Sipes', 'Doloremque', 'Tale They were indeed a queer-looking party that assembled on the door of the doors of the party went back to yesterday, because I was thinking I should think very likely it can talk: at any rate.', '9798853156258', 'http://placeimg.com/480/640/any', '2010-12-18', 'Et Eveniet', NULL, NULL),
(48, 'I\'ll just see what.', 'Lelia Ratke', 'Sint', 'I had not got into it), and handed them round as prizes. There was a large mustard-mine near here. And the Eaglet bent down its head impatiently, and walked off; the Dormouse go on in a tone of the.', '9797911055359', 'http://placeimg.com/480/640/any', '1979-03-05', 'Eos Et', NULL, NULL),
(49, 'SAID was, \'Why is.', 'Murl Legros', 'Est', 'But she did not like to show you! A little bright-eyed terrier, you know, as we were. My notion was that you had been looking over their heads. She felt very lonely and low-spirited. In a minute or.', '9797411369413', 'http://placeimg.com/480/640/any', '1976-11-23', 'A Nesciunt', NULL, NULL),
(50, 'The Queen turned.', 'Ressie Deckow', 'Quam', 'I beg your acceptance of this was his first speech. \'You should learn not to be ashamed of yourself,\' said Alice, \'I\'ve often seen a good deal worse off than before, as the Rabbit, and had just.', '9780315956353', 'http://placeimg.com/480/640/any', '1972-01-03', 'Tempora Temporibus', NULL, NULL),
(51, 'Alice, \'as all the.', 'Nils Koss', 'Non', 'Queen?\' said the King, who had been for some time with great curiosity. \'Soles and eels, of course,\' the Dodo replied very politely, \'for I can\'t see you?\' She was a general clapping of hands at.', '9793287312577', 'http://placeimg.com/480/640/any', '1992-02-02', 'Dolorem Ut', NULL, NULL),
(52, 'I was sent for.\'.', 'Adah Collins', 'Molestias', 'After a while, finding that nothing more happened, she decided to remain where she was near enough to try the thing yourself, some winter day, I will tell you my history, and you\'ll understand why.', '9799189078238', 'http://placeimg.com/480/640/any', '2016-10-11', 'Nisi Sint', NULL, NULL),
(53, 'Alice. \'That\'s the.', 'Brooklyn Feil', 'Quam', 'Alice was so much into the earth. Let me see: I\'ll give them a railway station.) However, she did not like to drop the jar for fear of killing somebody, so managed to put it in asking riddles that.', '9793069088485', 'http://placeimg.com/480/640/any', '1982-04-30', 'Sapiente Ut', NULL, NULL),
(54, 'NEVER get any.', 'Garth Runolfsson', 'Est', 'As she said to the Mock Turtle; \'but it sounds uncommon nonsense.\' Alice said to the door. \'Call the next witness. It quite makes my forehead ache!\' Alice watched the White Rabbit hurried by--the.', '9781657910331', 'http://placeimg.com/480/640/any', '2002-02-14', 'Veritatis Iure', NULL, NULL),
(55, 'And the moral of.', 'Arielle O\'Hara', 'Est', 'Alice; \'that\'s not at all like the look of the officers of the other side, the puppy began a series of short charges at the Caterpillar\'s making such a thing. After a while she was ready to talk.', '9799515852945', 'http://placeimg.com/480/640/any', '1983-07-01', 'Nihil Et', NULL, NULL),
(56, 'But, now that I\'m.', 'Era Bruen', 'Et', 'Alice whispered, \'that it\'s done by everybody minding their own business!\' \'Ah, well! It means much the most confusing thing I ever heard!\' \'Yes, I think I can reach the key; and if it makes me grow.', '9785874730635', 'http://placeimg.com/480/640/any', '1974-05-21', 'Perferendis Recusandae', NULL, NULL),
(57, 'Why, there\'s.', 'Josefina Bernhard', 'Voluptas', 'Rabbit\'s little white kid gloves in one hand and a piece of rudeness was more and more faintly came, carried on the English coast you find a pleasure in all my limbs very supple By the time he had.', '9791841612538', 'http://placeimg.com/480/640/any', '1983-07-27', 'Quam Molestiae', NULL, NULL),
(58, 'Mock Turtle had.', 'Georgette Kessler', 'Cumque', 'Some of the way to hear his history. I must have prizes.\' \'But who is to find quite a crowd of little birds and beasts, as well as she spoke; \'either you or your head must be getting somewhere near.', '9782966161544', 'http://placeimg.com/480/640/any', '1974-06-21', 'Sit Itaque', NULL, NULL),
(59, 'Duchess, who.', 'Godfrey Stamm', 'Maxime', 'Will you, won\'t you, will you, old fellow?\' The Mock Turtle\'s Story \'You can\'t think how glad I am now? That\'ll be a grin, and she looked up, but it all is! I\'ll try if I fell off the subjects on.', '9781114143470', 'http://placeimg.com/480/640/any', '2017-09-28', 'Est Placeat', NULL, NULL),
(60, 'Majesty,\' he.', 'May Greenholt', 'Magnam', 'Go on!\' \'I\'m a poor man,\' the Hatter went on, \'What HAVE you been doing here?\' \'May it please your Majesty,\' he began. \'You\'re a very respectful tone, but frowning and making quite a large crowd.', '9790811312683', 'http://placeimg.com/480/640/any', '1996-09-03', 'Doloremque Corporis', NULL, NULL),
(61, 'Cheshire cat,\'.', 'Queen Schulist', 'Voluptatibus', 'Latin Grammar, \'A mouse--of a mouse--to a mouse--a mouse--O mouse!\') The Mouse only shook its head down, and felt quite unhappy at the stick, running a very decided tone: \'tell her something about.', '9797660279150', 'http://placeimg.com/480/640/any', '1991-09-06', 'At Ut', NULL, NULL),
(62, 'The first thing.', 'Ephraim Medhurst', 'Dignissimos', 'Mock Turtle. \'Seals, turtles, salmon, and so on.\' \'What a curious plan!\' exclaimed Alice. \'And ever since that,\' the Hatter went on, \'--likely to win, that it\'s hardly worth while finishing the.', '9797886965257', 'http://placeimg.com/480/640/any', '1979-02-08', 'Voluptas Placeat', NULL, NULL),
(63, 'Queen jumped up.', 'Kellie Kshlerin', 'Nobis', 'I\'ll eat it,\' said the Hatter: \'let\'s all move one place on.\' He moved on as he spoke, and added \'It isn\'t mine,\' said the March Hare. Alice was beginning to feel a little startled when she was.', '9789130990252', 'http://placeimg.com/480/640/any', '2020-08-16', 'Et Ipsam', NULL, NULL),
(64, 'I should like to.', 'Myron Zulauf', 'Quibusdam', 'I ever was at in all my life, never!\' They had a bone in his throat,\' said the Dodo. Then they both sat silent and looked along the sea-shore--\' \'Two lines!\' cried the Gryphon. \'They can\'t have.', '9793867492125', 'http://placeimg.com/480/640/any', '1998-11-19', 'Veritatis Tempore', NULL, NULL),
(65, 'I could show you.', 'Everett Larkin', 'Sint', 'NOT be an old Turtle--we used to it!\' pleaded poor Alice in a tone of delight, and rushed at the window, and one foot up the fan she was looking about for a minute, while Alice thought to herself.', '9794240691197', 'http://placeimg.com/480/640/any', '1975-06-20', 'Amet Sit', NULL, NULL),
(66, 'King. \'Nearly two.', 'Curt Larson', 'Voluptatum', 'No, I\'ve made up my mind about it; and the happy summer days. THE.', '9784531295678', 'http://placeimg.com/480/640/any', '2022-12-26', 'Repellat Optio', NULL, NULL),
(67, 'Alice rather.', 'Danika Ledner', 'Dolore', 'It was high time you were or might have been changed several times since then.\' \'What do you know what to do that,\' said the King. \'Nothing whatever,\' said Alice. \'Anything you like,\' said the.', '9781045447463', 'http://placeimg.com/480/640/any', '1983-12-02', 'Autem Maxime', NULL, NULL),
(68, 'Alice dodged.', 'Granville Pfannerstill', 'Temporibus', 'Mock Turtle, \'but if you\'ve seen them at dinn--\' she checked herself hastily. \'I don\'t like it, yer honour, at all, at all!\' \'Do as I was thinking I should think!\' (Dinah was the King; \'and don\'t be.', '9782104373754', 'http://placeimg.com/480/640/any', '1998-08-18', 'Rem Et', NULL, NULL),
(69, 'Alice said very.', 'Hazel Witting', 'Rerum', 'So Alice got up and picking the daisies, when suddenly a footman because he taught us,\' said the Footman, and began to tremble. Alice looked down at them, and all her coaxing. Hardly knowing what.', '9780645976335', 'http://placeimg.com/480/640/any', '2009-05-23', 'Alias Atque', NULL, NULL),
(70, 'Queens, and among.', 'Gwen Terry', 'Nam', 'He sent them word I had to run back into the roof bear?--Mind that loose slate--Oh, it\'s coming down! Heads below!\' (a loud crash)--\'Now, who did that?--It was Bill, I fancy--Who\'s to go from here?\'.', '9787161881051', 'http://placeimg.com/480/640/any', '1987-06-12', 'Ex Reprehenderit', NULL, NULL),
(71, 'I\'ll get into that.', 'Amina Grady', 'At', 'It was opened by another footman in livery, with a trumpet in one hand and a bright idea came into Alice\'s shoulder as she ran; but the great question is, Who in the book,\' said the Mock Turtle.', '9795328175318', 'http://placeimg.com/480/640/any', '2000-06-26', 'Tenetur Ut', NULL, NULL),
(72, 'PLEASE mind what.', 'Alessandro Bode', 'Neque', 'Majesty,\' the Hatter asked triumphantly. Alice did not seem to see a little queer, won\'t you?\' \'Not a bit,\' she thought there was hardly room for this, and after a few yards off. The Cat seemed to.', '9785758999776', 'http://placeimg.com/480/640/any', '2016-08-23', 'Id Porro', NULL, NULL),
(73, 'This time Alice.', 'Franco Hagenes', 'Illo', 'Alice; \'only, as it\'s asleep, I suppose it doesn\'t mind.\' The table was a dead silence instantly, and neither of the wood for fear of their hearing her; and when she went in search of her ever.', '9780985721107', 'http://placeimg.com/480/640/any', '1997-09-20', 'Voluptatem Doloribus', NULL, NULL),
(74, 'Caterpillar. Alice.', 'Casandra Grant', 'Aut', 'Allow me to sell you a song?\' \'Oh, a song, please, if the Mock Turtle, \'they--you\'ve seen them, of course?\' \'Yes,\' said Alice, timidly; \'some of the tale was something like this:-- \'Fury said to.', '9799417605281', 'http://placeimg.com/480/640/any', '1984-04-24', 'Expedita Earum', NULL, NULL),
(75, 'Alice. \'I\'m glad.', 'Maxie Kilback', 'Adipisci', 'Ma!\' said the Mock Turtle sighed deeply, and began, in a frightened tone. \'The Queen of Hearts were seated on their faces, and the Queen, and Alice, were in custody and under sentence of execution.', '9782325453105', 'http://placeimg.com/480/640/any', '2014-10-04', 'Voluptatem Corporis', NULL, NULL),
(76, 'Mock Turtle Soup.', 'Jaime Haley', 'Exercitationem', 'I only wish they WOULD not remember the simple rules their friends had taught them: such as, \'Sure, I don\'t believe there\'s an atom of meaning in it,\' but none of my own. I\'m a deal faster than it.', '9781358064760', 'http://placeimg.com/480/640/any', '1984-03-24', 'Alias Tempore', NULL, NULL),
(77, 'The Mouse did not.', 'Adrianna Denesik', 'Facilis', 'Everything is so out-of-the-way down here, and I\'m sure _I_ shan\'t be able! I shall fall right THROUGH the earth! How funny it\'ll seem to see if she meant to take the roof of the cakes, and was a.', '9796852770420', 'http://placeimg.com/480/640/any', '1977-08-10', 'Qui Esse', NULL, NULL),
(78, 'Queen. \'I never.', 'Sallie Hamill', 'Ut', 'Alice, whose thoughts were still running on the table. \'Have some wine,\' the March Hare will be When they take us up and said, \'That\'s right, Five! Always lay the blame on others!\' \'YOU\'D better not.', '9793758571328', 'http://placeimg.com/480/640/any', '1996-08-14', 'Sit Occaecati', NULL, NULL),
(79, 'Dormouse denied.', 'Olen Schiller', 'In', 'The Mouse looked at each other for some while in silence. At last the Mouse, in a very small cake, on which the wretched Hatter trembled so, that he had never seen such a subject! Our family always.', '9798717327060', 'http://placeimg.com/480/640/any', '1989-07-10', 'Quas Aut', NULL, NULL),
(80, 'But she went down.', 'Merritt Luettgen', 'Vel', 'I\'m I, and--oh dear, how puzzling it all seemed quite dull and stupid for life to go on. \'And so these three weeks!\' \'I\'m very sorry you\'ve been annoyed,\' said Alice, as she had nothing else to say.', '9782471949583', 'http://placeimg.com/480/640/any', '1980-05-27', 'Dignissimos Quia', NULL, NULL),
(81, 'However, when they.', 'Stuart Toy', 'Ex', 'O Mouse!\' (Alice thought this a very difficult game indeed. The players all played at once and put it into his cup of tea, and looked at each other for some way of expressing yourself.\' The baby.', '9781003053712', 'http://placeimg.com/480/640/any', '2022-05-04', 'Et Est', NULL, NULL),
(82, 'BEST butter,\' the.', 'Chanelle Kunze', 'Quia', 'Alice did not quite sure whether it would be worth the trouble of getting up and straightening itself out again, so she went back to the game, the Queen was silent. The King turned pale, and shut.', '9793531697931', 'http://placeimg.com/480/640/any', '1985-06-25', 'Non Atque', NULL, NULL),
(83, 'Miss, this here.', 'Brain Wisoky', 'Similique', 'SHOES.\' the Gryphon said, in a loud, indignant voice, but she remembered that she had not got into it), and sometimes she scolded herself so severely as to size,\' Alice hastily replied; \'at.', '9788184551525', 'http://placeimg.com/480/640/any', '1973-05-23', 'Ut Quidem', NULL, NULL),
(84, 'Hardly knowing.', 'Cesar Kunde', 'Molestiae', 'He was looking down at them, and all the while, till at last in the window?\' \'Sure, it\'s an arm, yer honour!\' \'Digging for apples, yer honour!\' (He pronounced it \'arrum.\') \'An arm, you goose! Who.', '9792747374100', 'http://placeimg.com/480/640/any', '1983-08-25', 'Rerum Voluptatem', NULL, NULL),
(85, 'Alice sadly. \'Hand.', 'Francisco Ruecker', 'Nisi', 'The Caterpillar and Alice could see her after the others. \'We must burn the house of the creature, but on second thoughts she decided to remain where she was, and waited. When the procession moved.', '9799666308070', 'http://placeimg.com/480/640/any', '1991-06-10', 'Sequi At', NULL, NULL),
(86, 'All on a bough of.', 'Sylvan Rolfson', 'Quos', 'I was sent for.\' \'You ought to be no use in the other: the Duchess said after a few minutes to see its meaning. \'And just as she spoke. \'I must be removed,\' said the Caterpillar contemptuously. \'Who.', '9791335433755', 'http://placeimg.com/480/640/any', '1989-12-24', 'Quod Autem', NULL, NULL),
(87, 'Hatter, it woke up.', 'Loma Sipes', 'Voluptas', 'Will you, won\'t you join the dance. Would not, could not, would not, could not, would not give all else for two reasons. First, because I\'m on the hearth and grinning from ear to ear. \'Please would.', '9784927597522', 'http://placeimg.com/480/640/any', '1994-01-13', 'Adipisci Et', NULL, NULL),
(89, 'Come on!\'.', 'Oran Reichert', 'Ut', 'King was the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' said the youth, \'as I mentioned before, And have grown most uncommonly fat; Yet you balanced an eel on the.', '9781606961810', 'http://placeimg.com/480/640/any', '1973-03-22', 'Voluptatem Magnam', NULL, NULL),
(90, 'Mock Turtle at.', 'Hailee Schuppe', 'Quam', 'TWO little shrieks, and more sounds of broken glass. \'What a funny watch!\' she remarked. \'There isn\'t any,\' said the Mock Turtle. \'She can\'t explain MYSELF, I\'m afraid, but you might knock, and I.', '9792149970177', 'http://placeimg.com/480/640/any', '1975-03-13', 'Magni Numquam', NULL, NULL),
(91, 'I suppose Dinah\'ll.', 'Zita Kerluke', 'Perferendis', 'Gryphon. \'How the creatures order one about, and shouting \'Off with their heads down! I am now? That\'ll be a queer thing, to be no use speaking to a shriek, \'and just as the soldiers had to stoop to.', '9786240226394', 'http://placeimg.com/480/640/any', '1970-03-23', 'Animi Autem', NULL, NULL),
(92, 'Cat: \'we\'re all.', 'Magdalen Stoltenberg', 'Et', 'Owl, as a lark, And will talk in contemptuous tones of her age knew the meaning of half those long words, and, what\'s more, I don\'t want to be?\' it asked. \'Oh, I\'m not used to say it over) \'--yes.', '9791752398149', 'http://placeimg.com/480/640/any', '2003-08-03', 'Rerum Autem', NULL, NULL),
(93, 'Alice remained.', 'Destiny Towne', 'In', 'The Mock Turtle\'s heavy sobs. Lastly, she pictured to herself how this same little sister of hers would, in the direction in which you usually see Shakespeare, in the world! Oh, my dear Dinah! I.', '9781133124979', 'http://placeimg.com/480/640/any', '2011-10-17', 'Odit Repellendus', NULL, NULL),
(94, 'Queen, tossing her.', 'Zane Cummings', 'Asperiores', 'I wish you could only hear whispers now and then Alice put down yet, before the trial\'s begun.\' \'They\'re putting down their names,\' the Gryphon at the door-- Pray, what is the reason they\'re called.', '9788449105999', 'http://placeimg.com/480/640/any', '1981-07-21', 'Corporis Sint', NULL, NULL),
(95, 'Turtle. \'Certainly.', 'Merle Kilback', 'Qui', 'Some of the cakes, and was beating her violently with its head, it WOULD twist itself round and swam slowly back to the heads of the window, I only knew the meaning of it now in sight, hurrying down.', '9793430905441', 'http://placeimg.com/480/640/any', '2014-09-16', 'Ad Voluptate', NULL, NULL),
(96, 'Stigand, the.', 'Brayan Roberts', 'Adipisci', 'And so it was very uncomfortable, and, as the Caterpillar decidedly, and the Mock Turtle: \'nine the next, and so on; then, when you\'ve cleared all the time she had never before seen a cat without a.', '9787482224513', 'http://placeimg.com/480/640/any', '2009-09-16', 'Et Nihil', NULL, NULL),
(97, 'How I wonder who.', 'Birdie Reinger', 'Incidunt', 'And with that she knew that were of the cattle in the kitchen. \'When I\'M a Duchess,\' she said to Alice, that she was beginning to get to,\' said the Mock Turtle; \'but it doesn\'t matter which way I.', '9786004774055', 'http://placeimg.com/480/640/any', '1975-08-16', 'Quam Quia', NULL, NULL),
(98, 'Alice gently.', 'Mona Gislason', 'Molestiae', 'Alice again, for this time she saw them, they were gardeners, or soldiers, or courtiers, or three of her age knew the meaning of it now in sight, hurrying down it. There could be beheaded, and that.', '9794125451892', 'http://placeimg.com/480/640/any', '1977-09-11', 'Nam Dolores', NULL, NULL),
(99, 'ALL RETURNED FROM.', 'Margaret Schuppe', 'Omnis', 'YOU must cross-examine the next moment a shower of little birds and animals that had slipped in like herself. \'Would it be murder to leave off this minute!\' She generally gave herself very good.', '9795406154266', 'http://placeimg.com/480/640/any', '1992-02-21', 'Animi Incidunt', NULL, NULL),
(100, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9794493854349', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(102, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9794493854341', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(103, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9794493854342', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(104, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9794493851342', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(105, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9797493851342', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(106, 'VERY much out of.', 'Aida Gerhold', 'Id', 'ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head through the doorway; \'and even if my head would go anywhere without a cat! It\'s the most interesting, and perhaps after all it.', '9784493851342', 'http://placeimg.com/480/640/any', '2004-11-06', 'Nostrum Aut', NULL, NULL),
(107, 'It was as much as.', 'Chasity Leannon', 'Cumque', 'ME\' were beautifully marked in currants. \'Well, I\'ll eat it,\' said the Footman, and began to get into that lovely garden. I think you\'d take a fancy to cats if you want to see you again, you dear.', '9794737795682', 'http://placeimg.com/480/640/any', '1970-03-28', 'Neque Id', NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
